const reading = [
    {
        id: "1",
        book_id: "67bcb06fdf4d28770e24db69",
        user_id: "67c6eddbd78a6c99f548753e",
        pages: 888,
        start_date: "2024-01-10",
        end_date: "2024-02-01",
        format: "Digital",
        type: "Saga",
        rating: 5,
        romantic: 4,
        happy: 3,
        sad: 2,
        spicy: 4,
        plot: 2,
        characters: ["Violet", "Xaden"],
        playlist: ["Canción 1", "Canción 2"],
        favoriteMoments: ["Momento 1", "Momento 2"],
    },
    {
        id: "2",
        book_id: "6",
        user_id: "1",
        pages: 496,
        start_date: "2024-02-01",
        end_date: "2024-02-10",
        format: "Fisico",
        type: "Saga",
        rating: 5,
        romantic: 4,
        happy: 4,
        sad: 3,
        spicy: 3,
        plot: 2,
        characters: ["Gibsie", "Claire"],
        playlist: ["Canción 1"],
        favoriteMoments: ["Momento 1", "Momento 2", "Momento 3"],
    },
];

export default reading;